// Downloads woff2 files for Comfortaa + Inter from Google Fonts,
// stores them in assets/fonts/, and writes a self-hosted @font-face CSS to src/fonts.css.
//
// Run: node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = join(__dirname, '..');
const FONTS_DIR = join(ROOT, 'assets', 'fonts');
const OUT_CSS   = join(ROOT, 'src', 'fonts.css');

// Modern UA -> Google returns woff2.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const GF_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Comfortaa:wght@400;500;700' +
  '&family=Inter:wght@400;500;600;700' +
  '&display=swap';

async function fetchText(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`GET ${url} -> ${r.status}`);
  return r.text();
}

async function fetchBuf(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`GET ${url} -> ${r.status}`);
  return new Uint8Array(await r.arrayBuffer());
}

function slugForFile(family, weight, subset, hash) {
  return `${family.toLowerCase()}-${subset}-${weight}-${hash}.woff2`;
}

async function main() {
  await mkdir(FONTS_DIR, { recursive: true });
  const css = await fetchText(GF_URL);

  // Split into @font-face blocks. Each block has a /* comment */ line above naming the subset.
  // Parse line-by-line, track current subset comment and current family/weight inside the block.
  const lines = css.split('\n');
  let currentSubset = 'latin';
  let block = null;
  const outBlocks = [];

  for (const line of lines) {
    const subsetMatch = line.match(/^\s*\/\*\s*([\w-]+)\s*\*\//);
    if (subsetMatch && !block) {
      currentSubset = subsetMatch[1];
      continue;
    }
    if (line.startsWith('@font-face')) {
      block = { subset: currentSubset, family: '', weight: '', srcUrl: '', text: line };
      continue;
    }
    if (block) {
      block.text += '\n' + line;
      const fm = line.match(/font-family:\s*'([^']+)'/);
      if (fm) block.family = fm[1];
      const wm = line.match(/font-weight:\s*(\d+)/);
      if (wm) block.weight = wm[1];
      const um = line.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      if (um) block.srcUrl = um[1];
      if (line.includes('}')) {
        outBlocks.push(block);
        block = null;
      }
    }
  }

  // Keep only the subsets that this site actually serves.
  // Drop greek/vietnamese to reduce repo size.
  const ALLOWED_SUBSETS = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

  // Download woff2 files and rewrite src to local path
  const seen = new Set();
  const rewritten = [];
  for (const b of outBlocks) {
    if (!b.srcUrl) continue;
    if (!ALLOWED_SUBSETS.has(b.subset)) continue;
    const hash = b.srcUrl.split('/').slice(-1)[0].split('.')[0].slice(-6); // last 6 chars of basename
    const fname = slugForFile(b.family, b.weight, b.subset, hash);
    const dest  = join(FONTS_DIR, fname);
    if (!seen.has(fname)) {
      const buf = await fetchBuf(b.srcUrl);
      await writeFile(dest, buf);
      seen.add(fname);
      console.log('saved', fname, '(', buf.byteLength, 'bytes )');
    }
    const newText = b.text.replace(
      /url\(https:\/\/[^)]+\.woff2\)/,
      `url('../assets/fonts/${fname}')`
    );
    rewritten.push(newText);
  }

  const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.
 * Re-run with: node scripts/fetch-fonts.mjs
 * Fonts: Comfortaa + Inter, latin + cyrillic subsets, self-hosted woff2.
 */\n\n`;
  await writeFile(OUT_CSS, header + rewritten.join('\n\n') + '\n');
  console.log('wrote', OUT_CSS);
  console.log('total files:', seen.size);
}

main().catch(err => { console.error(err); process.exit(1); });
